### PR TITLE
Pcb

### PR DESCRIPTION
**Pull request by kimanimichael**

### CODE REVIEW

**Review by SammyOina — CHANGES_REQUESTED** [review]
are the .zip files especially the ones in the backup dir necessary to make changes or view the schematic or PCB. if not add them to gitignore. The same goes for other files that are not necessary.
Other than that schematic lgtm

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
Add `techweekpcb-backups` to `.gitignore`

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
LEDs aren't connected to MCU

**Comment by Mike-Kimani** [comment]
> are the .zip files especially the ones in the backup dir necessary to make changes or view the schematic or PCB. if not add them to gitignore. The same goes for other files that are not necessary. Other than that schematic lgtm

Have added all to git ignore

**Comment by Mike-Kimani** [comment]
> Add `techweekpcb-backups` to `.gitignore`

Yes.

**Comment by Mike-Kimani** [comment]
> LEDs aren't connected to MCU

Done now.

**Comment by Mike-Kimani** [comment]
#14

**Review by WashingtonKK — APPROVED** [review]

**Review by rodneyosodo — APPROVED** [review]

**Pull request merged**
